### ISSUE TITLE
Warrior: Intimidating Shout (https://wotlkdb.com/?spell=5246)

### ISSUE THREAD

**Issue by tebbeh-dev** [Duellum/BugsWOTLK#3]
When Intimidating Shout is casted your opponent are supposed to flee in fear. They get feared but stand in the same place as they get feared.

**Comment by Duellum** [comment]
It's working as intended. 

- Source: https://wow.gamepedia.com/Intimidating_Shout
> On Patch 1.1.0 (2004-11-07): Moved to level 22, no longer causes the targeted enemy to run in fear, but will cower in fear. The cowering effect is broken by damage.
