### ISSUE TITLE
Quest: Lambs To The Slaughter (https://wotlkdb.com/?quest=12722)

### ISSUE THREAD

**Issue by tebbeh-dev** [Duellum/BugsWOTLK#4]
Citizen of New Avalon (https://wotlkdb.com/?npc=28559) is a low level mob and hits like a 80 elite. I may have missunderstood this quest but I dont remember them hit that hard.

![opera_2019-12-28_15-12-07](https://user-images.githubusercontent.com/46937387/71544928-0cc75280-2985-11ea-8849-dcf6179655dc.jpg)

**Comment by Duellum** [comment]
It's OK, they hit hard because they got enrage buff, anyways I recommend you to find another mobs that aren't 20 in same group, check https://youtu.be/-OhWNoxFTdY?t=178.
